# `ndarray`

Reference: [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [1]:
import numpy as np

While a Python list can contain different data types within a single list, all of the elements in a **NumPy array** should be homogeneous. NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types.

You might occasionally hear an array referred to as a `ndarray`, which is shorthand for **N-dimensional array**. An N-dimensional array is simply an array with any number of dimensions. You might also hear **1-D**, or one-dimensional array, **2-D**, or two-dimensional array, and so on.

A **vector** is an array with a single dimension, hence there’s no difference between row and column vectors.

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a.ndim

1

In [5]:
a.shape

(4,)

A **matrix** refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term **tensor** is also commonly used.

## Axes

In NumPy, dimensions are called **axes**. This means that if you have a 2D array that looks like this:

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6]])

Your array has 2 axes.

In [8]:
a.ndim

2

The first axis has a length of 2 and the second axis has a length of 3.

In [9]:
a.shape

(2, 3)

The `numpmy.concatenate()` function joins a sequence of arrays along an existing axis. With `axis=0`, the arrays are joined along the first axis.

In [10]:
b = np.array([[7, 8, 9]])

In [11]:
b.shape

(1, 3)

In [12]:
c = np.concatenate((a, b), axis=0)

In [13]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
c.shape

(3, 3)

When concatenating two arrays with `axis=1`, the arrays must have the same length of the first axis.

In [15]:
d = np.array([[10], [11], [12]])

In [16]:
d

array([[10],
       [11],
       [12]])

In [17]:
d.shape

(3, 1)

In [18]:
e = np.concatenate((d, c), axis=1)

In [19]:
e

array([[10,  1,  2,  3],
       [11,  4,  5,  6],
       [12,  7,  8,  9]])

In [20]:
e.shape

(3, 4)

## Accessing data along axes

In [21]:
rng = np.random.default_rng(0)

In [22]:
a3d = rng.random((2, 4, 3))

In [23]:
a3d

array([[[0.63696169, 0.26978671, 0.04097352],
        [0.01652764, 0.81327024, 0.91275558],
        [0.60663578, 0.72949656, 0.54362499],
        [0.93507242, 0.81585355, 0.0027385 ]],

       [[0.85740428, 0.03358558, 0.72965545],
        [0.17565562, 0.86317892, 0.54146122],
        [0.29971189, 0.42268722, 0.02831967],
        [0.12428328, 0.67062441, 0.64718951]]])

Accessing a single value:

In [24]:
a3d[1, 1, 2]

0.5414612202490917

Getting all values along `axis=2` gives you a **vector**:

In [25]:
a3d[1, 1, :]

array([0.17565562, 0.86317892, 0.54146122])

Also along `axis=1`:

In [26]:
a3d[1, :, 2]

array([0.72965545, 0.54146122, 0.02831967, 0.64718951])

And along `axis=0`:

In [27]:
a3d[:, 1, 2]

array([0.91275558, 0.54146122])

Accessing along two axes, for instance `axis=0` and `axis=2`, yields a **matrix**:

In [28]:
a3d[:, 1, :]

array([[0.01652764, 0.81327024, 0.91275558],
       [0.17565562, 0.86317892, 0.54146122]])

Also along `axis=0` and `axis=1`:

In [29]:
a3d[:, :, 2]

array([[0.04097352, 0.91275558, 0.54362499, 0.0027385 ],
       [0.72965545, 0.54146122, 0.02831967, 0.64718951]])

And along `axis=1` and `axis=2`:

In [30]:
a3d[1, :, :]

array([[0.85740428, 0.03358558, 0.72965545],
       [0.17565562, 0.86317892, 0.54146122],
       [0.29971189, 0.42268722, 0.02831967],
       [0.12428328, 0.67062441, 0.64718951]])