# Python Bracket Operators

- [`list` comprehensions](https://python-reference.readthedocs.io/en/latest/docs/comprehensions/list_comprehension.html)
- [`list` literals](https://python-reference.readthedocs.io/en/latest/docs/list/literals.html)
- [`[]` indexing](https://python-reference.readthedocs.io/en/latest/docs/brackets/indexing.html)
- [`[]` slicing](https://python-reference.readthedocs.io/en/latest/docs/brackets/slicing.html)
- [`[]` key lookup](https://python-reference.readthedocs.io/en/latest/docs/brackets/key_lookup.html)
- [`[]` ellipsis](https://python-reference.readthedocs.io/en/latest/docs/brackets/ellipsis.html)

## `list` comprehensions

Returns a list based on existing iterables.

```
[expr(var) for var in input [predicate][, ...]]
```

<dl>
    <dt>expr</dt>
    <dd>Optional. An output expression producing members of the new set from members of the input set that satisfy the predicate expression.</dd>
    <dt>var</dt>
    <dd>Required. Variable representing members of an input set.</dd>
    <dt>input</dt>
    <dd>Required. Represents the input set.</dd>
    <dt>predicate</dt>
    <dd>Optional. Expression acting as a filter on members of the input set.</dd>
    <dt>[, ...]</dt>
    <dd>Optional. Another nested comprehension.</dd>
<dl>

In [1]:
[n**2 for n in range(7) if n > 3]

[16, 25, 36]

In [2]:
[[m, n] for m in (1, 2) for n in (3, 4)]

[[1, 3], [1, 4], [2, 3], [2, 4]]

## `list` literals

`List`s can be initialized separating enclosing comma separated values in sequence brackets `[]`.

In [3]:
l = [1, 2]

In [4]:
l

[1, 2]

In [5]:
a = 'AA'

In [6]:
b = 'BB'

In [7]:
l = [a, b]

In [8]:
l

['AA', 'BB']

## `[]` indexing

Gives access to a sequence's element.

```
sequence [index]
```

<dl>
    <dt>index></dt>
    <dd>Index of the item you want to access. Must be an integer.</dd>
</dl>

The built-in fundamental sequence types are:
- strings &mdash; `str` and `unicode`
- arrays &mdash; `list` and `tuple`

Since all sequences are ordered and indexed arrays of objects, each object stored in a sequence has it’s associated index number - positive one, zero indexed and starting from left, and the negative one starting at -1 from the right.

In [9]:
s = 'ABCDEFG'

In [10]:
s[0]

'A'

In [11]:
s[-1]

'G'

Index lookups can be chained to access nested containers.

In [12]:
a2d = ((0, 1), (2, 3))

In [13]:
a2d[1][1]

3

Since `list`s are mutable, indexes can be used for item assignment or deletion.

In [14]:
l = [2, 3, 5, 7]

In [15]:
l[0] = 'ABCD'

In [16]:
l

['ABCD', 3, 5, 7]

In [17]:
del l[2]

In [18]:
l

['ABCD', 3, 7]

## `[]` slicing

Gives access to a specified *range* of sequence's elements.

```
sequence [start: stop [:step]]
```

<dl>
    <dt>start</dt>
    <dd>Optional. Starting index of the slice. Defaults to 0.</dd>
    <dt>stop</dt>
    <dd>Optional. The last index of the slice or the number of items to get. Defaults to len(sequence).</dd>
    <dt>step</dt>
    <dd>Optional. Extended slice syntax. Step value of the slice. Defaults to 1.</dd>
</dl>

In [19]:
'ABCDEFG'[2:5]

'CDE'

In [20]:
'ABCDEFG'[:5]

'ABCDE'

In [21]:
'ABCDEFG'[2:]

'CDEFG'

In [22]:
'ABCDEFG'[::2]

'ACEG'

Slices can be used to replace multiple items.

In [23]:
l = ['a', 'b', 'c', 'd']

In [24]:
l[:2] = ('e', 'f')

In [25]:
l

['e', 'f', 'c', 'd']

In [26]:
l[1:3] = ('g', 'h', 'i', 'j')

In [27]:
l

['e', 'g', 'h', 'i', 'j', 'd']

Multiple items can be deleted.

In [28]:
del l[2:5]

In [29]:
l

['e', 'g', 'd']

## `[]` key lookup

The `[]` key lookup operator returns the value associated with the given key.

In [30]:
{'a': 1, 'b': 2, 'c': 3, 'd': 4}['b']

2

## `[]` ellipsis

Ellipsis is used for slicing multidimensional numpy arrays.
The ellipsis syntax may be used to indicate selecting in full any remaining unspecified dimensions.

In [31]:
import numpy as np

In [32]:
n = np.arange(16).reshape(2, 2, 2, 2)

In [33]:
n

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [34]:
n[1, ..., 1]

array([[ 9, 11],
       [13, 15]])

In [35]:
n[1,:, :,1]

array([[ 9, 11],
       [13, 15]])